# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Lint Code Base
# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
permissions: read-all
jobs:
  get-sloc:
    name: Count Lines of Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # 6.0.0
        with:
          go-version: ">=1.20.0"
      - name: Install dependencies
        run: go install github.com/boyter/scc/v3@latest
      - name: Run scc tool
        run: scc --format wide
  check-broken-links:
    name: Check documentation external links
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          persist-credentials: false
      - name: Check broken links
        uses: tcort/github-action-markdown-link-check@f3d33029dca1c4a24b87e2df648f9f4604ef6533 # 1.1.1
  check-super-linter:
    name: Check syntax (super-linter)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      models: read
      issues: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          persist-credentials: false
      - name: Run super-linter validation
        id: linter-validation
        uses: super-linter/super-linter@2bdd90ed3262e023ac84bf8fe35dc480721fc1f2 # 8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          VALIDATE_GO_MODULES: false
          VALIDATE_BIOME_FORMAT: false
          KUBERNETES_KUBECONFORM_OPTIONS: "-ignore-missing-schemas"
          DEFAULT_BRANCH: ${{ github.head_ref || github.ref_name }}
      - name: Analyze linter results with
        id: ai-linter-analysis
        if: failure()
        uses: actions/ai-inference@a1c11829223a786afe3b5663db904a3aa1eac3a2 # 2.0.1
        with:
          prompt-file: .github/prompts/review-issue.prompt.yml
          input: ${{ steps.linter-validation.outputs.output }}
      - uses: jayqi/failed-build-issue-action@1a893bbf43ef1c2a8705e2b115cd4f0fe3c5649b # 1.2.0
        if: failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title-template: "Super-linter has failed"
          body-template: |
            The linter step has failed. Please check for new major versions and update manually.

            Please check the [logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.

            ## AI Analysis of Linter Failures
            ${{ steps.ai-linter-analysis.outputs.output }}
